### ISSUE TITLE
Suggestion - Display date on list view 

### ISSUE THREAD

**Issue by lui2k** [TheBiochemic/tickets-rs#4]
Within a bucket where I can see a list of my tasks/bugs, could there be a filter/category to see a date associated with that bug.  It would help me recognise when a task is due, so I can look at urgent bugs first.

![image](https://github.com/TheBiochemic/tickets-rs/assets/37487891/c1c5e2ff-5a62-4e39-92a9-3442bfb84010)

**Comment by TheBiochemic** [comment]
as far as i remember, there is also a filter option, that basically can filter tickets, that are due in X Days.

in the FIlters you could do for example `[[your_adapter_name: assigned_to(::me) due_in_days(7)]]` to get all tickets that are due in 7 days or less. I will probably write a bit of documentation, how to properly use these filters, but for now i hope that helps!

The view has been added in d66473974ed38990034889148ec627d3fe4c21c1, see https://github.com/TheBiochemic/tickets-rs/tree/releases for new versions
